// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using a;

#nullable disable

namespace HW5_GalavonniWilson.Migrations
{
    [DbContext(typeof(PatientDB))]
    [Migration("20240223213126_createpatientdb")]
    partial class createpatientdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("a.Patient", b =>
                {
                    b.Property<string>("PID")
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgeLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("PID");

                    b.ToTable("patients");
                });
#pragma warning restore 612, 618
        }
    }
}
